### ISSUE TITLE
Binding is wrong in 3.1.1

### ISSUE THREAD

**Issue by dhh** [rails/web-console#199]
![image](https://cloud.githubusercontent.com/assets/2741/15682258/1f401420-275d-11e6-9735-7d0391a4eebe.png)

The binding in the console is inside the Post object, rather than at the callsite. And it doesn't change when you navigate the backtrace lines.

**Comment by gsamokovarov** [comment]
We're trying to tackle that with PRs like #198. We used to always select the very exception binding for code evaluation, while we're showing the first `Application Trace` as the more interesting code snippet in the Rails error pages. WIth #198, we tried to pick the binding of one of the `Application Trace` and with a future PR we'll try to better map bindings with traces, as we currently have more traces than bindings and just looking them up by indexes doesn't work properly. You can easily see that trying to choose one of last traces for an exception. The binding will most probably be wrong.

 We're aware of it and will try to rush this up for the final Rails 5 release.

**Comment by dhh** [comment]
Excellent, thanks! Wanted to show off web-console in the new intro video, and just got a little stumped on this.

**Comment by gsamokovarov** [comment]
David, I have release `3.2.0` which will choose the binding of the snippet we actually see on the error page. While we still have some work to do to make sure we always choose the proper binding if you navigate the stack trace (by better mapping the traces from their `__FILE__` and  `__LINE__` instead of their indexes), I'm closing this one for now. I think the biggest show stopper for `web-console` was when you typed something and it didn't work, because of the naively chosen wrong binding and hopefully, this can help.

Please feel free to reopen if the issue still persists, so we can reiterate before Rails 5 final.
