### ISSUE TITLE
Pressing the backspace key while in the web console causes the page to go back.

### ISSUE THREAD

**Issue by agustaf9** [rails/web-console#206]
With the recent update to chrome an extension is required to use backspace to go back. Using that extension causes backspace to go back even when typing in the web-console. This problem also occurs when using the Vivaldi web browser without the extension.

**Comment by gsamokovarov** [comment]
Pinging @sh19910711 here.

**Comment by sh19910711** [comment]
I'm not sure what is a critical problem yet, but I'm facing with a similar problem when I create auto-completion feature of web-console in #205. However, I think my case might be more natural as a browser's behavior because it was caused after typing TAB key.

@agustaf9 Could you please give us more details? It would be helpful if we could know about your extension names, situations or something else.

**Comment by agustaf9** [comment]
[This](https://github.com/oslego/chrome-backspace-back/blob/master/contentscript.js) is the extension I am using for chrome.

**Comment by sh19910711** [comment]
@agustaf9 Thanks for the information.

**Comment by bovender** [comment]
I am facing the same problem. Any solution in sight?

**Comment by Frexuz** [comment]
Same, with that extension :(

**Comment by agustaf9** [comment]
[This](https://chrome.google.com/webstore/detail/go-back-with-backspace/eekailopagacbcdloonjhbiecobagjci) extension works.
