### ISSUE TITLE
how to use pry with web-console?

### ISSUE THREAD

**Issue by catmando** [rails/web-console#223]
I see the pry adapter is deprecated.  It sounds like its "easy" to use pry with webconsole... how?

**Comment by mjhoy** [comment]
I'm not exactly sure about how to get pry running in the web console itself. But if you add `pry` to your gemfile's development dependencies, and then type `binding.pry` in the web console, you will have access to a pry session in the shell where you run `rails server`.

**Comment by gsamokovarov** [comment]
`web-console` started as a Google Summer of Code project back in 2013! Since we didn't had a clear vision of what we really wanted it to do at that time, we prototyped a couple of ideas. You can [see](https://github.com/rails/web-console/tree/v0.1.0) [how](https://github.com/rails/web-console/tree/v1.0.4) web-console got to its [current](https://github.com/rails/web-console/tree/v3.0.0) shape. The [web-console-pry](https://github.com/gsamokovarov/web-console-pry) project was a plugin for the [initial](https://github.com/rails/web-console/tree/v0.1.0) release, however it's been long deprecated.

**Comment by eloyesp** [comment]
Hi, it would be nice to have some instructions added on the readme about how to config what console to run (irb or pry)

**Comment by 23tux** [comment]
I'd also like some guidance, on how to use pry with web console. @eloyesp did you find out how?

**Comment by gsamokovarov** [comment]
`binding.pry` and `binding.irb` (it's a builtin Pry alternative) stop the program and let you investigate it through a terminal. Web Console leaves the program running and give you the ability to introspect it post-factum. You cannot use Web Console as a remote TTY for Pry or IRB, they are different tools.
