### ISSUE TITLE
Faulty message: Web Console is activated in the test environment

### ISSUE THREAD

**Issue by krtschmr** [rails/web-console#322]
![image](https://user-images.githubusercontent.com/13366714/195818727-3adb01ad-281c-4717-88be-75491a06b939.png)

Rails 6.1, ruby 2.7

i'm very confused about this

doing as i got told, same outcome.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/13366714/195819361-2f2e7508-6e80-4251-b5a5-1895acef4e87.png">

**Comment by gsamokovarov** [comment]
Are you sure `web-console` is duplicated and not present in a `:test` group as well.

**Comment by krtschmr** [comment]
that i'm certain. after further investigation, i believe it might has to do with the `dotenv` gem

**Comment by gsamokovarov** [comment]
`dotenv` is setting the envs in Ruby runtime. It has to be required first, it may happen that the `web-console` gem is loaded alongside `dotenv` through Bundler and only afterwards, the `RAILS_ENV` env is set. Because of `dotenv` being a runtime dependency, I prefer to set environment variables with tools like [direnv tool](https://direnv.net).

We really don't want the `web-console` code in the test environment. I'll close the ticket.
