### ISSUE TITLE
support for most common keys and shortcuts

### ISSUE THREAD

**Issue by Nowaker** [rails/web-console#44]
- Delete
- Home
- End

And these known commonly from shells and irb:
- ^W
- ^U
- ^C
- ^R + typing

**Comment by king601** [comment]
Hi all /  @gsamokovarov,

I would like to ask to re-consider adding support for at least ^C, I see it was closed in #93.

My reasons are the following:

1. Beginners when they run into an error commonly will use the console on the error page to troubleshoot what they needed to fix, once they get it working they try and copy it out to update their code. Once people see it doesn't support copying out, as a beginner it reduces the reason to use it (web console).

2. Even as a non-beginner, who has just accepted that you can't copy in it, I still find myself trying to copy out because every other time I'm in a terminal it lets me copy a snippet out to reuse it elsewhere. It seems intuitive to expect you can copy out of the terminal.

I understand the point of not wanting to confuse with others keybindings, but it already supports ^V  (paste)... so it seems logical to expect the copy functionality to make it in.

On that note, if this is something you'd be okay with, I do not mind working on a PR to add ^C support, it would greatly improve my own development workflow, just let me know. 

Thanks ❤️

**Comment by gsamokovarov** [comment]
My frontend skills are quite rusty, but if someone else wants to take a stab at this and fix it once and for all, I'll be extremely grateful!

**Comment by causztic** [comment]
Just curious, I am able to ^C the text on the console on Chrome.. Am I missing something painfully obvious here? 😆
